Redesign of Signup/Login Pages
jb162/fun-kickoff-project pull request #1
Opened 2021-11-09 00:20 UTC by jb162

Redesigned the signup and login pages, including the AuthHeader, according to mockups. Added logo and buttons to AuthHeader.

### What this PR does (required):
- redesigned login and signup pages according to mockups, (as close as possible)
- redesigned AuthHeader (logo, "become a sitter", login & signup buttons, box-shadow)

### Screenshots / Videos (front-end only):
- Login Page Screenshot
![login-screenshot](https://user-images.githubusercontent.com/78042694/140837972-63f1fae5-2904-4f54-822d-22510cb7148d.png)
- Signup Page Screenshot
![signup-screenshot](https://user-images.githubusercontent.com/78042694/140838005-a6563973-1680-4b62-a314-797404c5546d.png)

### Any information needed to test this feature (required):
- Signup: create a new account using the Signup page
- Login: login to your new account using the Login page

### Any issues with the current functionality (optional):
- I am unsure of the exact style specifications defined by the mockup. I tried to create the redesign as close as I could to the mockup but a style guide would be very helpful.
- replaced TextField component with FormControl, FormLabel, OutlinedInput, and FormHelperText to achieve the desired styling
- this may cause problems if other code references these components by TextField instead of id or className
<img width="518" alt="Screen Shot 2021-11-08 at 4 16 55 PM" src="https://user-images.githubusercontent.com/78042694/140838581-e0c6e30c-04f2-43c8-bdbe-cc8b7ca6034f.png">

2021-11-09 17:07 UTC, ezeilo-su requested changes
Looks good! Please checkout the comments below and make the necessary changes.
Happy coding!

2021-11-09 18:43 UTC, rajivtitus commented on client/src/components/AuthHeader/AuthHeader.tsx
> +      <img className={classes.headerLogo} src={logo} />
It is a good practice to add 'alt' attributes to images :)

2021-11-09 18:53 UTC, rajivtitus reviewed
UI looks good, nice work here! Please have a look and address comment from Sunday and myself. Thank you!

2021-11-09 18:53 UTC, rajivtitus commented on client/src/components/AuthHeader/AuthHeader.tsx
> +          <Button className={classes.loginBtn}>LOGIN</Button>
The MUI Button and react-router Link can be combined:

`
<Button component={Link} to="/login" color="primary">login</Button>
`

Ditto throughout!

2021-11-09 18:53 UTC, rajivtitus commented on client/src/components/AuthHeader/AuthHeader.tsx
> +          <Button className={classes.loginBtn}>LOGIN</Button>
Please avoid using CAPITALCASE for text, some screen readers interpret this text as abbreviations, you can resort to using a CSS class to transform text instead.

2021-11-09 18:53 UTC, rajivtitus commented on client/src/components/AuthHeader/useStyles.ts
> +    justifyContent: 'space-between',
Most of these styles can be applied to the Box component directly

Eg: 
`
<Box display="flex" alignItems="center".....></Box>
`

2021-11-09 18:53 UTC, rajivtitus commented on client/src/components/AuthHeader/useStyles.ts
> +      backgroundColor: '#f04040',
You can set colours within MUI's theme and use the theme to apply them  which ensures consistency across the app :)

2021-11-09 18:53 UTC, rajivtitus commented on client/src/pages/Login/LoginForm/LoginForm.tsx
> +              <Typography className={classes.label}>EMAIL ADDRESS</Typography>
Same as comment above for CAPITALCASE text

2021-11-09 18:53 UTC, rajivtitus commented on client/src/pages/Login/useStyles.ts
> +  loginForm: {
Most of the styles within this class can be directly applied to the Box component 😄

2021-11-09 18:53 UTC, rajivtitus commented on client/src/pages/SignUp/useStyles.ts
> +  signupForm: {
Most of the styles within this class can be applied to the Box component directly :)

2021-11-10 14:57 UTC, rajivtitus commented on client/src/components/AuthHeader/useStyles.ts
> +  authHeader: {},
Please remove empty the empty CSS class here :)

2021-11-10 15:00 UTC, rajivtitus approved these changes
Great work making those changes 💯 
Just some minor cleanup to do prior to merging 👍🏽

2021-11-10 15:00 UTC, rajivtitus commented on client/src/pages/Login/useStyles.ts
> +  authWrapper: {},
Please remove empty class

2021-11-10 15:00 UTC, rajivtitus commented on client/src/pages/SignUp/useStyles.ts
> +  authWrapper: {},
Please remove

2021-11-10 19:44 UTC, merged